### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by ftomassetti** [cmcqueen/simplerandom#2]
hi, do you support cmake?

**Comment by cmcqueen** [comment]
No, cmake is currently not supported. (I've never used it myself.) Is the current autotools support unsuitable for your platform, and is cmake better?

On 4 Jan 2015, at 12:01 am, "Federico Tomassetti" <notifications@github.com<mailto:notifications@github.com>> wrote:


hi, do you support cmake?

-
